---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kafka-ui-kumkeehyun-github-com-v1-role
  failurePolicy: Fail
  name: vrole.kb.io
  rules:
  - apiGroups:
    - kafka-ui.kumkeehyun.github.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - roles
  sideEffects: None
