# permissions for end users to view replicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: replicaset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafka-ui-operator
    app.kubernetes.io/part-of: kafka-ui-operator
    app.kubernetes.io/managed-by: kustomize
  name: replicaset-viewer-role
rules:
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - replicasets/status
  verbs:
  - get
