---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - kafka-ui.kumkeehyun.github.com
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
